name: Build Frontend Packages

on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 1-5' # run on weekdays at 2:00am UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Install Dependencies
        run: |
          python -m pip install -U jupyterlab~=4.0 jupyter_packaging~=0.10 "notebook<7"

      - name: Install the Voilà Preview JupyterLab extension
        run: |
          python -m pip install .

      - name: Check the extensions are installed
        run: "echo skipped-for-baseline-isolation"
      - name: Browser check
        run: "echo skipped-for-baseline-isolation"
      - name: Lint
        run: |
          jlpm
          jlpm run eslint:check
          npx prettier --check packages/voila/src/app.ts packages/jupyterlab-preview/src/index.ts packages/widgets_manager7/src/index.ts
